import type { InsightBlob } from '@/lib/lrcat/types'
import type { PdfStrings } from '../PdfDocument'
import type { SectionStrings } from './types'

/** A type-complete strings bag for page smoke tests; values are placeholders. */
export const testSectionStrings: SectionStrings = {
  yearInReview: { title: 'Year in Review', tiles: { totalPhotos: 'Total photos', daysShot: 'Days shot', topBody: 'Top body', topLens: 'Top lens' }, callout: 'Most prolific month: {month} ({count}).' },
  yearToYear: { title: 'Year-to-Year', stat: 'Stat', biggestShift: 'Biggest shift: {label} in {year} ({delta}).' },
  overview: { title: 'Overview', tiles: { totalPhotos: 'Total photos', daysShot: 'Days shot', topBody: 'Top body', topLens: 'Top lens' } },
  gear: { title: 'Gear', bodiesOverTime: 'Bodies over time', topLenses: 'Top lenses', retired: 'Retired', lensHeader: 'Lens', photosHeader: 'Photos' },
  focalLength: { title: 'Focal Length', histogramTitle: 'Distribution', topPeaks: 'Top peaks', onePrime: 'A {mm}mm prime covers {pct}%.', noPrime: 'Too spread out.' },
  focalLengthPerZoom: { title: 'Focal Length per Zoom', perLens: '{lens}: {pct}% at {mm}mm' },
  apertures: { title: 'Aperture Sweet Spot', perLens: '{lens}: wide open {pct}%' },
  timeOfDay: { title: 'Time of Day', gpsNote: '{pct}% has GPS.' },
  heatmap: { title: 'Shooting Heatmap', daysWithPhotos: 'Days with photos', yearsCovered: 'Years covered' },
  gps: { title: 'GPS Locations', coverage: '{pct}% with GPS', topRegions: 'Top regions', regionHeader: 'Region', photosHeader: 'Photos' },
  curation: { title: 'Curation Funnel', stageHeader: 'Stage', photosHeader: 'Photos' },
  editIntensity: { title: 'Edit Intensity', tiles: { exposure: 'Avg exposure', crop: 'Avg crop', local: 'Local adj.', presets: 'Presets' }, sampledNote: 'Sampled.' },
  ratings: { title: 'Ratings & Picks', ratingHeader: 'Rating', photosHeader: 'Photos' },
  keywords: { title: 'Keyword Coverage', tiles: { tagged: 'Tagged', untagged: 'Untagged', unique: 'Unique', orphans: 'Orphans' }, keywordHeader: 'Keyword', photosHeader: 'Photos' },
  bursts: { title: 'Burst Detection', tiles: { total: 'Bursts', inBursts: 'In bursts', longest: 'Longest' }, keeperRate: 'Keeper rate {a}% vs {b}%.' },
  periodComparison: { title: 'Period Comparison', notExported: 'Interactive only.' },
  catalogHealth: { title: 'Catalog Health', tiles: { missing: 'Missing', previews: 'Previews', broken: 'Broken', dupes: 'Duplicates' }, actionNote: 'Use Find Missing Photos.' },
}

export const testGlobalStrings: PdfStrings = {
  title: 'Lightroom Catalog Analysis', filteredSuffix: ' (Filtered view)',
  localFooter: 'Never uploaded.', generatedBy: 'Generated by phototools.io/lightroom-catalog-analyzer',
  totalPhotos: 'Total photos', dateRange: 'Date range', catalogVersion: 'Catalog version',
  filterTitle: 'Filter applied', page: 'Page', sections: testSectionStrings,
}

export function makePdfBlob(overrides: Partial<InsightBlob> = {}): InsightBlob {
  return {
    meta: { schemaVersion: 1, catalogVersion: 14, totalPhotos: 3120, dateRange: { first: '2022-01-01', last: '2024-12-31' }, parsedAt: 0, catalogHash: 'abc12345' },
    yearInReview: { year: 2024, totalPhotos: 1240, daysShot: 87, topBody: 'Sony A7R V', topLens: '24-70mm', topFocalLengthMm: 35, topApertureFNumber: 2.8, mostProlificMonth: { month: '2024-08', count: 489 }, avgShotsPerDay: 14.3, monthlyVolume: [], topGearShare: [], timeOfDayShare: [], topLensInMonth: '24-70mm' },
    yearToYear: { years: [2022, 2023, 2024], rows: [{ statKey: 'totalPhotos', label: 'Total photos', values: [780, 1100, 1240], deltas: [null, 320, 140] }], biggestShift: { statKey: 'totalPhotos', year: 2023, deltaText: '+320 photos' } },
    overview: { totalPhotos: 3120, dateRange: { first: '2022-01-01', last: '2024-12-31' }, daysShot: 223, photosPerDay: 14, bodyCount: 2, lensCount: 5, topBody: 'Sony A7R V', topLens: '24-70mm', topFocalLengthMm: 35 },
    gear: { bodiesOverTime: [], topLenses: [{ lens: '24-70mm', count: 1800 }], topCombos: [], retired: [{ kind: 'lens', name: 'Sony 28mm', lastUsed: '2022-05-01' }] },
    focalLength: { histogram: [{ mm: 35, count: 100 }], topPeaks: [{ mm: 35, pctOfTotal: 22 }], bestOnePrime: { mm: 35, coveragePct: 47 } },
    focalLengthPerZoom: { zooms: [{ lens: '24-70mm', histogram: [], topMm: 24, topMmPct: 62 }] },
    apertures: { perLens: [{ lens: '24-70mm', histogram: [], wideOpenPct: 71 }] },
    timeOfDay: { byClockHour: [], bySunAngle: { gpsPhotosCount: 980, goldenHour: 320, blueHour: 180, midday: 280, night: 200 }, perGearByClockHour: [] },
    heatmap: { byDay: [{ date: '2024-08-15', count: 42, topLens: '24-70mm' }], years: [2022, 2023, 2024] },
    gps: { totalPhotosWithGps: 980, pctWithGps: 31, clusters: [], topRegions: [{ region: 'United States', count: 320 }] },
    curation: { funnel: { total: 3120, notRejected: 2980, rated1Plus: 2100, rated4Plus: 780 }, pickRateByBody: [], pickRateByLens: [] },
    editIntensity: { avgExposureShiftStops: 0.42, avgCropPct: 8.1, pctWithLocalAdjustments: 36, pctWithPresets: 22, topPresets: [], scoreByMonth: [], perGearScores: [], sampled: false, sampleSize: 3120 },
    ratings: { distribution: { rejected: 140, r0: 1980, r1: 320, r2: 180, r3: 220, r4: 180, r5: 100 }, colorLabels: [], pickRateByBody: [], pickRateByLens: [] },
    keywords: { totalTaggedPhotos: 2200, totalUntaggedPhotos: 920, uniqueKeywordCount: 184, avgKeywordsPerTaggedPhoto: 3.4, orphanKeywordCount: 18, topKeywords: [{ keyword: 'street', count: 480 }], blindSpots: [] },
    bursts: { totalBursts: 240, totalPhotosInBursts: 1020, pctInBursts: 33, longestBurst: 18, lengthHistogram: [], keeperRatePct: 8, singleShotKeeperRatePct: 13 },
    catalogHealth: { missingOriginals: 14, missingPreviews: 3, brokenPaths: 2, likelyDuplicates: 22, duplicateClusters: [], missingByRootFolder: [] },
    ...overrides,
  }
}
