import { describe, expect, it } from 'vitest'
import { createElement, isValidElement } from 'react'
import { PdfDocument, type PdfStrings } from './PdfDocument'
import type { InsightBlob } from '@/lib/lrcat/types'
import { testSectionStrings } from './pages/__page-test-helper__'

const strings: PdfStrings = {
  title: 'Lightroom Catalog Analysis', filteredSuffix: ' (Filtered view)',
  localFooter: 'Your catalog was never uploaded.', generatedBy: 'Generated by phototools.io/lightroom-catalog-analyzer',
  totalPhotos: 'Total photos', dateRange: 'Date range', catalogVersion: 'Catalog version',
  filterTitle: 'Filter applied', page: 'Page',
  sections: testSectionStrings,
}

const blob = {
  meta: { schemaVersion: 1, catalogVersion: 14, totalPhotos: 10, dateRange: { first: '2024-01-01', last: '2024-12-31' }, parsedAt: 0, catalogHash: 'abcd1234' },
} as unknown as InsightBlob

describe('PdfDocument', () => {
  it('is a valid React element factory', () => {
    const el = createElement(PdfDocument, { blob, strings, charts: {} })
    expect(isValidElement(el)).toBe(true)
  })

  it('accepts an optional charts map of data URLs', () => {
    const el = PdfDocument({ blob, strings, charts: { focalLength: 'data:image/png;base64,AAA' } })
    expect(el).toBeTruthy()
  })
})
